# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import headmotion_pb2 as headmotion__pb2


class MotionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.MoveTo = channel.unary_unary(
        '/motionService.MotionService/MoveTo',
        request_serializer=headmotion__pb2.MoveToRequest.SerializeToString,
        response_deserializer=headmotion__pb2.MoveToResponse.FromString,
        )
    self.PositioningData = channel.unary_stream(
        '/motionService.MotionService/PositioningData',
        request_serializer=headmotion__pb2.PositioningDataRequest.SerializeToString,
        response_deserializer=headmotion__pb2.PositioningDataResponse.FromString,
        )
    self.GetPosition = channel.unary_unary(
        '/motionService.MotionService/GetPosition',
        request_serializer=headmotion__pb2.GetPositionRequest.SerializeToString,
        response_deserializer=headmotion__pb2.GetPositionResponse.FromString,
        )
    self.NewGroup = channel.unary_unary(
        '/motionService.MotionService/NewGroup',
        request_serializer=headmotion__pb2.NewGroupRequest.SerializeToString,
        response_deserializer=headmotion__pb2.NewGroupResponse.FromString,
        )
    self.ListGroups = channel.unary_unary(
        '/motionService.MotionService/ListGroups',
        request_serializer=headmotion__pb2.ListGroupsRequest.SerializeToString,
        response_deserializer=headmotion__pb2.ListGroupsResponse.FromString,
        )
    self.UpdateGroup = channel.unary_unary(
        '/motionService.MotionService/UpdateGroup',
        request_serializer=headmotion__pb2.UpdateGroupRequest.SerializeToString,
        response_deserializer=headmotion__pb2.UpdateGroupResponse.FromString,
        )
    self.DeleteGroups = channel.unary_unary(
        '/motionService.MotionService/DeleteGroups',
        request_serializer=headmotion__pb2.DeleteGroupsRequest.SerializeToString,
        response_deserializer=headmotion__pb2.DeleteGroupsResponse.FromString,
        )
    self.ListGroupTargets = channel.unary_unary(
        '/motionService.MotionService/ListGroupTargets',
        request_serializer=headmotion__pb2.ListGroupTargetsRequest.SerializeToString,
        response_deserializer=headmotion__pb2.ListGroupTargetsResponse.FromString,
        )
    self.UpdateGroupTargets = channel.unary_unary(
        '/motionService.MotionService/UpdateGroupTargets',
        request_serializer=headmotion__pb2.UpdateGroupTargetsRequest.SerializeToString,
        response_deserializer=headmotion__pb2.UpdateGroupTargetsResponse.FromString,
        )


class MotionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def MoveTo(self, request, context):
    """移动功能
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PositioningData(self, request, context):
    """持续监听位置消息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPosition(self, request, context):
    """获取当前位置信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def NewGroup(self, request, context):
    """创建组
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListGroups(self, request, context):
    """获取组列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateGroup(self, request, context):
    """更新组信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteGroups(self, request, context):
    """删除组列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListGroupTargets(self, request, context):
    """获取组动作点列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateGroupTargets(self, request, context):
    """更新组动作点列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MotionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'MoveTo': grpc.unary_unary_rpc_method_handler(
          servicer.MoveTo,
          request_deserializer=headmotion__pb2.MoveToRequest.FromString,
          response_serializer=headmotion__pb2.MoveToResponse.SerializeToString,
      ),
      'PositioningData': grpc.unary_stream_rpc_method_handler(
          servicer.PositioningData,
          request_deserializer=headmotion__pb2.PositioningDataRequest.FromString,
          response_serializer=headmotion__pb2.PositioningDataResponse.SerializeToString,
      ),
      'GetPosition': grpc.unary_unary_rpc_method_handler(
          servicer.GetPosition,
          request_deserializer=headmotion__pb2.GetPositionRequest.FromString,
          response_serializer=headmotion__pb2.GetPositionResponse.SerializeToString,
      ),
      'NewGroup': grpc.unary_unary_rpc_method_handler(
          servicer.NewGroup,
          request_deserializer=headmotion__pb2.NewGroupRequest.FromString,
          response_serializer=headmotion__pb2.NewGroupResponse.SerializeToString,
      ),
      'ListGroups': grpc.unary_unary_rpc_method_handler(
          servicer.ListGroups,
          request_deserializer=headmotion__pb2.ListGroupsRequest.FromString,
          response_serializer=headmotion__pb2.ListGroupsResponse.SerializeToString,
      ),
      'UpdateGroup': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGroup,
          request_deserializer=headmotion__pb2.UpdateGroupRequest.FromString,
          response_serializer=headmotion__pb2.UpdateGroupResponse.SerializeToString,
      ),
      'DeleteGroups': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteGroups,
          request_deserializer=headmotion__pb2.DeleteGroupsRequest.FromString,
          response_serializer=headmotion__pb2.DeleteGroupsResponse.SerializeToString,
      ),
      'ListGroupTargets': grpc.unary_unary_rpc_method_handler(
          servicer.ListGroupTargets,
          request_deserializer=headmotion__pb2.ListGroupTargetsRequest.FromString,
          response_serializer=headmotion__pb2.ListGroupTargetsResponse.SerializeToString,
      ),
      'UpdateGroupTargets': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateGroupTargets,
          request_deserializer=headmotion__pb2.UpdateGroupTargetsRequest.FromString,
          response_serializer=headmotion__pb2.UpdateGroupTargetsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'motionService.MotionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
