// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: camera.proto

/*
Package cameraService is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package cameraService

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_CameraService_LatestImage_0(ctx context.Context, marshaler runtime.Marshaler, client CameraServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq LatestImageRequest
	var metadata runtime.ServerMetadata

	msg, err := client.LatestImage(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

// RegisterCameraServiceHandlerFromEndpoint is same as RegisterCameraServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterCameraServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterCameraServiceHandler(ctx, mux, conn)
}

// RegisterCameraServiceHandler registers the http handlers for service CameraService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterCameraServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterCameraServiceHandlerClient(ctx, mux, NewCameraServiceClient(conn))
}

// RegisterCameraServiceHandlerClient registers the http handlers for service CameraService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "CameraServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "CameraServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "CameraServiceClient" to call the correct interceptors.
func RegisterCameraServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client CameraServiceClient) error {

	mux.Handle("GET", pattern_CameraService_LatestImage_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_CameraService_LatestImage_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_CameraService_LatestImage_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_CameraService_LatestImage_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"api", "v2", "camera", "image"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_CameraService_LatestImage_0 = runtime.ForwardResponseMessage
)
