# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import expression_pb2 as expression__pb2


class ExpressionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PlayExpressions = channel.unary_unary(
        '/expressionService.ExpressionService/PlayExpressions',
        request_serializer=expression__pb2.PlayExpressionsRequest.SerializeToString,
        response_deserializer=expression__pb2.PlayExpressionsResponse.FromString,
        )
    self.StopExpression = channel.unary_unary(
        '/expressionService.ExpressionService/StopExpression',
        request_serializer=expression__pb2.StopExpressionRequest.SerializeToString,
        response_deserializer=expression__pb2.StopExpressionResponse.FromString,
        )
    self.UploadExpressionFile = channel.unary_unary(
        '/expressionService.ExpressionService/UploadExpressionFile',
        request_serializer=expression__pb2.UploadExpressionFileRequest.SerializeToString,
        response_deserializer=expression__pb2.UploadExpressionFileResponse.FromString,
        )
    self.Rename = channel.unary_unary(
        '/expressionService.ExpressionService/Rename',
        request_serializer=expression__pb2.RenameRequest.SerializeToString,
        response_deserializer=expression__pb2.RenameResponse.FromString,
        )
    self.ListExpressions = channel.unary_unary(
        '/expressionService.ExpressionService/ListExpressions',
        request_serializer=expression__pb2.ListExpressionsRequest.SerializeToString,
        response_deserializer=expression__pb2.ListExpressionsResponse.FromString,
        )
    self.DeleteExpressions = channel.unary_unary(
        '/expressionService.ExpressionService/DeleteExpressions',
        request_serializer=expression__pb2.DeleteExpressionsRequest.SerializeToString,
        response_deserializer=expression__pb2.DeleteExpressionsResponse.FromString,
        )


class ExpressionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PlayExpressions(self, request, context):
    """播放表情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StopExpression(self, request, context):
    """停止表情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadExpressionFile(self, request, context):
    """上传表情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Rename(self, request, context):
    """表情重命名
    >= v1.1.0
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListExpressions(self, request, context):
    """获取表情数据
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteExpressions(self, request, context):
    """删除表情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExpressionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PlayExpressions': grpc.unary_unary_rpc_method_handler(
          servicer.PlayExpressions,
          request_deserializer=expression__pb2.PlayExpressionsRequest.FromString,
          response_serializer=expression__pb2.PlayExpressionsResponse.SerializeToString,
      ),
      'StopExpression': grpc.unary_unary_rpc_method_handler(
          servicer.StopExpression,
          request_deserializer=expression__pb2.StopExpressionRequest.FromString,
          response_serializer=expression__pb2.StopExpressionResponse.SerializeToString,
      ),
      'UploadExpressionFile': grpc.unary_unary_rpc_method_handler(
          servicer.UploadExpressionFile,
          request_deserializer=expression__pb2.UploadExpressionFileRequest.FromString,
          response_serializer=expression__pb2.UploadExpressionFileResponse.SerializeToString,
      ),
      'Rename': grpc.unary_unary_rpc_method_handler(
          servicer.Rename,
          request_deserializer=expression__pb2.RenameRequest.FromString,
          response_serializer=expression__pb2.RenameResponse.SerializeToString,
      ),
      'ListExpressions': grpc.unary_unary_rpc_method_handler(
          servicer.ListExpressions,
          request_deserializer=expression__pb2.ListExpressionsRequest.FromString,
          response_serializer=expression__pb2.ListExpressionsResponse.SerializeToString,
      ),
      'DeleteExpressions': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteExpressions,
          request_deserializer=expression__pb2.DeleteExpressionsRequest.FromString,
          response_serializer=expression__pb2.DeleteExpressionsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'expressionService.ExpressionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
