// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package cameraService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListDatesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDatesRequest) Reset()         { *m = ListDatesRequest{} }
func (m *ListDatesRequest) String() string { return proto.CompactTextString(m) }
func (*ListDatesRequest) ProtoMessage()    {}
func (*ListDatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *ListDatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDatesRequest.Unmarshal(m, b)
}
func (m *ListDatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDatesRequest.Marshal(b, m, deterministic)
}
func (m *ListDatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDatesRequest.Merge(m, src)
}
func (m *ListDatesRequest) XXX_Size() int {
	return xxx_messageInfo_ListDatesRequest.Size(m)
}
func (m *ListDatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDatesRequest proto.InternalMessageInfo

type ListDatesResponse struct {
	// 日期 e.g. [2019-01-01, 2019-01-02]
	Dates                []string `protobuf:"bytes,1,rep,name=dates,proto3" json:"dates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDatesResponse) Reset()         { *m = ListDatesResponse{} }
func (m *ListDatesResponse) String() string { return proto.CompactTextString(m) }
func (*ListDatesResponse) ProtoMessage()    {}
func (*ListDatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *ListDatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDatesResponse.Unmarshal(m, b)
}
func (m *ListDatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDatesResponse.Marshal(b, m, deterministic)
}
func (m *ListDatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDatesResponse.Merge(m, src)
}
func (m *ListDatesResponse) XXX_Size() int {
	return xxx_messageInfo_ListDatesResponse.Size(m)
}
func (m *ListDatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDatesResponse proto.InternalMessageInfo

func (m *ListDatesResponse) GetDates() []string {
	if m != nil {
		return m.Dates
	}
	return nil
}

type ListVideosRequest struct {
	// 开始时间
	// 默认为当日00:00:00
	// 格式 2019-01-02_03:04:05
	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	// 结束时间
	// 默认为当日23:59:59
	// 格式 2019-01-02_03:04:05
	End                  string   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVideosRequest) Reset()         { *m = ListVideosRequest{} }
func (m *ListVideosRequest) String() string { return proto.CompactTextString(m) }
func (*ListVideosRequest) ProtoMessage()    {}
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *ListVideosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVideosRequest.Unmarshal(m, b)
}
func (m *ListVideosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVideosRequest.Marshal(b, m, deterministic)
}
func (m *ListVideosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVideosRequest.Merge(m, src)
}
func (m *ListVideosRequest) XXX_Size() int {
	return xxx_messageInfo_ListVideosRequest.Size(m)
}
func (m *ListVideosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVideosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVideosRequest proto.InternalMessageInfo

func (m *ListVideosRequest) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *ListVideosRequest) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type ListVideosResponse struct {
	// e.g. [2019-01-01/00:00:00.mp4, 2019-01-01/00:10:00.mp4]
	Videos               []string `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVideosResponse) Reset()         { *m = ListVideosResponse{} }
func (m *ListVideosResponse) String() string { return proto.CompactTextString(m) }
func (*ListVideosResponse) ProtoMessage()    {}
func (*ListVideosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *ListVideosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVideosResponse.Unmarshal(m, b)
}
func (m *ListVideosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVideosResponse.Marshal(b, m, deterministic)
}
func (m *ListVideosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVideosResponse.Merge(m, src)
}
func (m *ListVideosResponse) XXX_Size() int {
	return xxx_messageInfo_ListVideosResponse.Size(m)
}
func (m *ListVideosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVideosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListVideosResponse proto.InternalMessageInfo

func (m *ListVideosResponse) GetVideos() []string {
	if m != nil {
		return m.Videos
	}
	return nil
}

type GetVideoFileRequest struct {
	// e.g. 2019-01-01/00:00:00.mp4
	Video                string   `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoFileRequest) Reset()         { *m = GetVideoFileRequest{} }
func (m *GetVideoFileRequest) String() string { return proto.CompactTextString(m) }
func (*GetVideoFileRequest) ProtoMessage()    {}
func (*GetVideoFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *GetVideoFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoFileRequest.Unmarshal(m, b)
}
func (m *GetVideoFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoFileRequest.Marshal(b, m, deterministic)
}
func (m *GetVideoFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoFileRequest.Merge(m, src)
}
func (m *GetVideoFileRequest) XXX_Size() int {
	return xxx_messageInfo_GetVideoFileRequest.Size(m)
}
func (m *GetVideoFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoFileRequest proto.InternalMessageInfo

func (m *GetVideoFileRequest) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

type GetVideoFileResponse struct {
	Chunk                []byte   `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoFileResponse) Reset()         { *m = GetVideoFileResponse{} }
func (m *GetVideoFileResponse) String() string { return proto.CompactTextString(m) }
func (*GetVideoFileResponse) ProtoMessage()    {}
func (*GetVideoFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *GetVideoFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoFileResponse.Unmarshal(m, b)
}
func (m *GetVideoFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoFileResponse.Marshal(b, m, deterministic)
}
func (m *GetVideoFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoFileResponse.Merge(m, src)
}
func (m *GetVideoFileResponse) XXX_Size() int {
	return xxx_messageInfo_GetVideoFileResponse.Size(m)
}
func (m *GetVideoFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoFileResponse proto.InternalMessageInfo

func (m *GetVideoFileResponse) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

type DeleteVideoFilesRequest struct {
	// e.g. [2019-01-01/00:00:00.mp4, 2019-12-01/22:10:00.mp4]
	Videos               []string `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVideoFilesRequest) Reset()         { *m = DeleteVideoFilesRequest{} }
func (m *DeleteVideoFilesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVideoFilesRequest) ProtoMessage()    {}
func (*DeleteVideoFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}

func (m *DeleteVideoFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVideoFilesRequest.Unmarshal(m, b)
}
func (m *DeleteVideoFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVideoFilesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVideoFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVideoFilesRequest.Merge(m, src)
}
func (m *DeleteVideoFilesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVideoFilesRequest.Size(m)
}
func (m *DeleteVideoFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVideoFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVideoFilesRequest proto.InternalMessageInfo

func (m *DeleteVideoFilesRequest) GetVideos() []string {
	if m != nil {
		return m.Videos
	}
	return nil
}

type DeleteVideoFilesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVideoFilesResponse) Reset()         { *m = DeleteVideoFilesResponse{} }
func (m *DeleteVideoFilesResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVideoFilesResponse) ProtoMessage()    {}
func (*DeleteVideoFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{7}
}

func (m *DeleteVideoFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVideoFilesResponse.Unmarshal(m, b)
}
func (m *DeleteVideoFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVideoFilesResponse.Marshal(b, m, deterministic)
}
func (m *DeleteVideoFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVideoFilesResponse.Merge(m, src)
}
func (m *DeleteVideoFilesResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVideoFilesResponse.Size(m)
}
func (m *DeleteVideoFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVideoFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVideoFilesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListDatesRequest)(nil), "cameraService.ListDatesRequest")
	proto.RegisterType((*ListDatesResponse)(nil), "cameraService.ListDatesResponse")
	proto.RegisterType((*ListVideosRequest)(nil), "cameraService.ListVideosRequest")
	proto.RegisterType((*ListVideosResponse)(nil), "cameraService.ListVideosResponse")
	proto.RegisterType((*GetVideoFileRequest)(nil), "cameraService.GetVideoFileRequest")
	proto.RegisterType((*GetVideoFileResponse)(nil), "cameraService.GetVideoFileResponse")
	proto.RegisterType((*DeleteVideoFilesRequest)(nil), "cameraService.DeleteVideoFilesRequest")
	proto.RegisterType((*DeleteVideoFilesResponse)(nil), "cameraService.DeleteVideoFilesResponse")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xd1, 0x4e, 0x1a, 0x41,
	0x14, 0x86, 0x3b, 0xd0, 0xd2, 0x70, 0x02, 0x09, 0x9d, 0x92, 0x76, 0xb3, 0xa1, 0x2d, 0x9d, 0x92,
	0xb6, 0x50, 0xc2, 0x16, 0xbc, 0xc3, 0x4b, 0x89, 0xc6, 0xc4, 0x2b, 0x48, 0xbc, 0xd0, 0xab, 0x91,
	0x3d, 0xc1, 0x8d, 0xb8, 0x83, 0x3b, 0x03, 0x0f, 0xe0, 0x23, 0xa8, 0x97, 0xbe, 0x95, 0xaf, 0xe0,
	0x83, 0x98, 0x9d, 0x19, 0x60, 0x59, 0x59, 0xbc, 0xe3, 0x9c, 0x7c, 0xff, 0xfc, 0x33, 0xff, 0xcf,
	0x42, 0x59, 0x2a, 0x11, 0xf1, 0x09, 0x76, 0x66, 0x91, 0x50, 0x82, 0x96, 0xc7, 0xfc, 0x1a, 0x23,
	0x3e, 0xc2, 0x68, 0x11, 0x8c, 0xd1, 0xad, 0x4d, 0x84, 0x98, 0x4c, 0xd1, 0xe3, 0xb3, 0xc0, 0xe3,
	0x61, 0x28, 0x14, 0x57, 0x81, 0x08, 0xa5, 0x81, 0x19, 0x85, 0xca, 0x49, 0x20, 0xd5, 0x80, 0x2b,
	0x94, 0x43, 0xbc, 0x99, 0xa3, 0x54, 0xac, 0x09, 0x9f, 0x12, 0x3b, 0x39, 0x13, 0xa1, 0x44, 0x5a,
	0x85, 0x0f, 0x7e, 0xbc, 0x70, 0x48, 0x3d, 0xff, 0xb7, 0x38, 0x34, 0x03, 0xdb, 0x37, 0xe8, 0x69,
	0xe0, 0xa3, 0x58, 0xea, 0x63, 0x54, 0x2a, 0x1e, 0x29, 0x87, 0xd4, 0x49, 0x8c, 0xea, 0x81, 0x56,
	0x20, 0x8f, 0xa1, 0xef, 0xe4, 0xf4, 0x2e, 0xfe, 0xc9, 0xda, 0x40, 0x93, 0x62, 0x6b, 0xf4, 0x05,
	0x0a, 0x0b, 0xbd, 0xb1, 0x4e, 0x76, 0x62, 0xff, 0xe0, 0xf3, 0x11, 0x1a, 0xf8, 0x30, 0x98, 0x62,
	0xc2, 0x4c, 0x03, 0x4b, 0x33, 0x3d, 0xb0, 0x36, 0x54, 0x37, 0xe1, 0xf5, 0x2b, 0xc6, 0x97, 0xf3,
	0xf0, 0x4a, 0xd3, 0xa5, 0xa1, 0x19, 0x58, 0x17, 0xbe, 0x0e, 0x70, 0x8a, 0x0a, 0x57, 0x82, 0xd5,
	0x5b, 0xb2, 0x6e, 0xe3, 0x82, 0xf3, 0x5a, 0x62, 0x4c, 0x7a, 0x77, 0xef, 0xe1, 0xe3, 0xc8, 0x54,
	0x42, 0x15, 0x14, 0x57, 0x59, 0xd2, 0x1f, 0x9d, 0x8d, 0x6a, 0x3a, 0xe9, 0xe4, 0xdd, 0x7a, 0x36,
	0x60, 0xce, 0x66, 0x8d, 0xdb, 0xa7, 0xe7, 0xfb, 0xdc, 0x77, 0x5a, 0xd3, 0x7d, 0x2e, 0x7a, 0x9e,
	0x11, 0x78, 0xf6, 0x2f, 0xe0, 0xe9, 0x5a, 0xe8, 0x23, 0x01, 0x58, 0x47, 0x4b, 0xb7, 0x1d, 0xbb,
	0x51, 0x99, 0xfb, 0x73, 0x07, 0x61, 0x9d, 0x8f, 0xb5, 0xf3, 0x01, 0xfd, 0x96, 0xe1, 0x6c, 0x82,
	0x39, 0x63, 0xcc, 0x02, 0xdd, 0xed, 0x40, 0x9f, 0xb4, 0xe8, 0x39, 0x94, 0x92, 0xed, 0x50, 0x96,
	0x72, 0xdf, 0xd2, 0xb3, 0xfb, 0x6b, 0x27, 0x63, 0xef, 0xf8, 0xee, 0x3f, 0xa1, 0x0f, 0x04, 0x2a,
	0xe9, 0x6a, 0xe8, 0xef, 0x94, 0x3a, 0xa3, 0x6e, 0xf7, 0xcf, 0x9b, 0x9c, 0x75, 0xf2, 0x74, 0x1a,
	0x4d, 0xd6, 0xd8, 0x99, 0x86, 0xe7, 0x6b, 0x7d, 0x9f, 0xb4, 0x2e, 0x0a, 0xfa, 0x7b, 0xdb, 0x7b,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xc6, 0xea, 0x84, 0xad, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	// 获取监控视频日期列表
	ListDates(ctx context.Context, in *ListDatesRequest, opts ...grpc.CallOption) (*ListDatesResponse, error)
	// 获取监控视频列表
	ListVideos(ctx context.Context, in *ListVideosRequest, opts ...grpc.CallOption) (*ListVideosResponse, error)
	// 获取监控视频文件
	GetVideoFile(ctx context.Context, in *GetVideoFileRequest, opts ...grpc.CallOption) (Storage_GetVideoFileClient, error)
	// 删除监控视频文件
	DeleteVideoFiles(ctx context.Context, in *DeleteVideoFilesRequest, opts ...grpc.CallOption) (*DeleteVideoFilesResponse, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) ListDates(ctx context.Context, in *ListDatesRequest, opts ...grpc.CallOption) (*ListDatesResponse, error) {
	out := new(ListDatesResponse)
	err := c.cc.Invoke(ctx, "/cameraService.Storage/ListDates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ListVideos(ctx context.Context, in *ListVideosRequest, opts ...grpc.CallOption) (*ListVideosResponse, error) {
	out := new(ListVideosResponse)
	err := c.cc.Invoke(ctx, "/cameraService.Storage/ListVideos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetVideoFile(ctx context.Context, in *GetVideoFileRequest, opts ...grpc.CallOption) (Storage_GetVideoFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[0], "/cameraService.Storage/GetVideoFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageGetVideoFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_GetVideoFileClient interface {
	Recv() (*GetVideoFileResponse, error)
	grpc.ClientStream
}

type storageGetVideoFileClient struct {
	grpc.ClientStream
}

func (x *storageGetVideoFileClient) Recv() (*GetVideoFileResponse, error) {
	m := new(GetVideoFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) DeleteVideoFiles(ctx context.Context, in *DeleteVideoFilesRequest, opts ...grpc.CallOption) (*DeleteVideoFilesResponse, error) {
	out := new(DeleteVideoFilesResponse)
	err := c.cc.Invoke(ctx, "/cameraService.Storage/DeleteVideoFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	// 获取监控视频日期列表
	ListDates(context.Context, *ListDatesRequest) (*ListDatesResponse, error)
	// 获取监控视频列表
	ListVideos(context.Context, *ListVideosRequest) (*ListVideosResponse, error)
	// 获取监控视频文件
	GetVideoFile(*GetVideoFileRequest, Storage_GetVideoFileServer) error
	// 删除监控视频文件
	DeleteVideoFiles(context.Context, *DeleteVideoFilesRequest) (*DeleteVideoFilesResponse, error)
}

// UnimplementedStorageServer can be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (*UnimplementedStorageServer) ListDates(ctx context.Context, req *ListDatesRequest) (*ListDatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDates not implemented")
}
func (*UnimplementedStorageServer) ListVideos(ctx context.Context, req *ListVideosRequest) (*ListVideosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVideos not implemented")
}
func (*UnimplementedStorageServer) GetVideoFile(req *GetVideoFileRequest, srv Storage_GetVideoFileServer) error {
	return status.Errorf(codes.Unimplemented, "method GetVideoFile not implemented")
}
func (*UnimplementedStorageServer) DeleteVideoFiles(ctx context.Context, req *DeleteVideoFilesRequest) (*DeleteVideoFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVideoFiles not implemented")
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_ListDates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ListDates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cameraService.Storage/ListDates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ListDates(ctx, req.(*ListDatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ListVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ListVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cameraService.Storage/ListVideos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ListVideos(ctx, req.(*ListVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetVideoFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetVideoFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).GetVideoFile(m, &storageGetVideoFileServer{stream})
}

type Storage_GetVideoFileServer interface {
	Send(*GetVideoFileResponse) error
	grpc.ServerStream
}

type storageGetVideoFileServer struct {
	grpc.ServerStream
}

func (x *storageGetVideoFileServer) Send(m *GetVideoFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_DeleteVideoFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVideoFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).DeleteVideoFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cameraService.Storage/DeleteVideoFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).DeleteVideoFiles(ctx, req.(*DeleteVideoFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cameraService.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDates",
			Handler:    _Storage_ListDates_Handler,
		},
		{
			MethodName: "ListVideos",
			Handler:    _Storage_ListVideos_Handler,
		},
		{
			MethodName: "DeleteVideoFiles",
			Handler:    _Storage_DeleteVideoFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetVideoFile",
			Handler:       _Storage_GetVideoFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage.proto",
}
