<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceset.proto

namespace FaceRecognition;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>faceRecognition.ListFaceDetailsResponse</code>
 */
class ListFaceDetailsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.faceRecognition.FaceSet face_set = 1;</code>
     */
    private $face_set = null;
    /**
     * Generated from protobuf field <code>repeated .faceRecognition.FaceDetail face_details = 2;</code>
     */
    private $face_details;
    /**
     * FaceSet中Face总数
     *
     * Generated from protobuf field <code>uint32 total = 3;</code>
     */
    private $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \FaceRecognition\FaceSet $face_set
     *     @type \FaceRecognition\FaceDetail[]|\Google\Protobuf\Internal\RepeatedField $face_details
     *     @type int $total
     *           FaceSet中Face总数
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Faceset::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.faceRecognition.FaceSet face_set = 1;</code>
     * @return \FaceRecognition\FaceSet
     */
    public function getFaceSet()
    {
        return $this->face_set;
    }

    /**
     * Generated from protobuf field <code>.faceRecognition.FaceSet face_set = 1;</code>
     * @param \FaceRecognition\FaceSet $var
     * @return $this
     */
    public function setFaceSet($var)
    {
        GPBUtil::checkMessage($var, \FaceRecognition\FaceSet::class);
        $this->face_set = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .faceRecognition.FaceDetail face_details = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFaceDetails()
    {
        return $this->face_details;
    }

    /**
     * Generated from protobuf field <code>repeated .faceRecognition.FaceDetail face_details = 2;</code>
     * @param \FaceRecognition\FaceDetail[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFaceDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \FaceRecognition\FaceDetail::class);
        $this->face_details = $arr;

        return $this;
    }

    /**
     * FaceSet中Face总数
     *
     * Generated from protobuf field <code>uint32 total = 3;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * FaceSet中Face总数
     *
     * Generated from protobuf field <code>uint32 total = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->total = $var;

        return $this;
    }

}

