# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='face.proto',
  package='faceRecognition',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nface.proto\x12\x0f\x66\x61\x63\x65Recognition\x1a\x1cgoogle/api/annotations.proto\"6\n\x0e\x43ompareRequest\x12\x11\n\tface_img1\x18\x01 \x01(\x0c\x12\x11\n\tface_img2\x18\x02 \x01(\x0c\"%\n\x0f\x43ompareResponse\x12\x12\n\nconfidence\x18\x01 \x01(\x02\"6\n\rSearchRequest\x12\x13\n\x0b\x66\x61\x63\x65_set_id\x18\x01 \x01(\t\x12\x10\n\x08\x66\x61\x63\x65_img\x18\x02 \x01(\x0c\"8\n\x0eSearchResponse\x12\x12\n\nconfidence\x18\x01 \x01(\x02\x12\x12\n\nface_token\x18\x02 \x01(\t2\xe7\x01\n\x0b\x46\x61\x63\x65Service\x12m\n\x07\x43ompare\x12\x1f.faceRecognition.CompareRequest\x1a .faceRecognition.CompareResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x14/api/v2/face/compare:\x01*\x12i\n\x06Search\x12\x1e.faceRecognition.SearchRequest\x1a\x1f.faceRecognition.SearchResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\"\x13/api/v2/face/search:\x01*b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_COMPAREREQUEST = _descriptor.Descriptor(
  name='CompareRequest',
  full_name='faceRecognition.CompareRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_img1', full_name='faceRecognition.CompareRequest.face_img1', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_img2', full_name='faceRecognition.CompareRequest.face_img2', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=115,
)


_COMPARERESPONSE = _descriptor.Descriptor(
  name='CompareResponse',
  full_name='faceRecognition.CompareResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='faceRecognition.CompareResponse.confidence', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=154,
)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='faceRecognition.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_set_id', full_name='faceRecognition.SearchRequest.face_set_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_img', full_name='faceRecognition.SearchRequest.face_img', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=210,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='SearchResponse',
  full_name='faceRecognition.SearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confidence', full_name='faceRecognition.SearchResponse.confidence', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_token', full_name='faceRecognition.SearchResponse.face_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=268,
)

DESCRIPTOR.message_types_by_name['CompareRequest'] = _COMPAREREQUEST
DESCRIPTOR.message_types_by_name['CompareResponse'] = _COMPARERESPONSE
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CompareRequest = _reflection.GeneratedProtocolMessageType('CompareRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPAREREQUEST,
  '__module__' : 'face_pb2'
  # @@protoc_insertion_point(class_scope:faceRecognition.CompareRequest)
  })
_sym_db.RegisterMessage(CompareRequest)

CompareResponse = _reflection.GeneratedProtocolMessageType('CompareResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPARERESPONSE,
  '__module__' : 'face_pb2'
  # @@protoc_insertion_point(class_scope:faceRecognition.CompareResponse)
  })
_sym_db.RegisterMessage(CompareResponse)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'face_pb2'
  # @@protoc_insertion_point(class_scope:faceRecognition.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'face_pb2'
  # @@protoc_insertion_point(class_scope:faceRecognition.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)



_FACESERVICE = _descriptor.ServiceDescriptor(
  name='FaceService',
  full_name='faceRecognition.FaceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=271,
  serialized_end=502,
  methods=[
  _descriptor.MethodDescriptor(
    name='Compare',
    full_name='faceRecognition.FaceService.Compare',
    index=0,
    containing_service=None,
    input_type=_COMPAREREQUEST,
    output_type=_COMPARERESPONSE,
    serialized_options=_b('\202\323\344\223\002\031\"\024/api/v2/face/compare:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='faceRecognition.FaceService.Search',
    index=1,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESPONSE,
    serialized_options=_b('\202\323\344\223\002\030\"\023/api/v2/face/search:\001*'),
  ),
])
_sym_db.RegisterServiceDescriptor(_FACESERVICE)

DESCRIPTOR.services_by_name['FaceService'] = _FACESERVICE

# @@protoc_insertion_point(module_scope)
