// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: face.proto

package faceRecognition;

public final class Face {
  private Face() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompareRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:faceRecognition.CompareRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes face_img1 = 1;</code>
     */
    com.google.protobuf.ByteString getFaceImg1();

    /**
     * <code>bytes face_img2 = 2;</code>
     */
    com.google.protobuf.ByteString getFaceImg2();
  }
  /**
   * Protobuf type {@code faceRecognition.CompareRequest}
   */
  public  static final class CompareRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:faceRecognition.CompareRequest)
      CompareRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CompareRequest.newBuilder() to construct.
    private CompareRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompareRequest() {
      faceImg1_ = com.google.protobuf.ByteString.EMPTY;
      faceImg2_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CompareRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CompareRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              faceImg1_ = input.readBytes();
              break;
            }
            case 18: {

              faceImg2_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return faceRecognition.Face.internal_static_faceRecognition_CompareRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return faceRecognition.Face.internal_static_faceRecognition_CompareRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              faceRecognition.Face.CompareRequest.class, faceRecognition.Face.CompareRequest.Builder.class);
    }

    public static final int FACE_IMG1_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString faceImg1_;
    /**
     * <code>bytes face_img1 = 1;</code>
     */
    public com.google.protobuf.ByteString getFaceImg1() {
      return faceImg1_;
    }

    public static final int FACE_IMG2_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString faceImg2_;
    /**
     * <code>bytes face_img2 = 2;</code>
     */
    public com.google.protobuf.ByteString getFaceImg2() {
      return faceImg2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!faceImg1_.isEmpty()) {
        output.writeBytes(1, faceImg1_);
      }
      if (!faceImg2_.isEmpty()) {
        output.writeBytes(2, faceImg2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!faceImg1_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, faceImg1_);
      }
      if (!faceImg2_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, faceImg2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof faceRecognition.Face.CompareRequest)) {
        return super.equals(obj);
      }
      faceRecognition.Face.CompareRequest other = (faceRecognition.Face.CompareRequest) obj;

      if (!getFaceImg1()
          .equals(other.getFaceImg1())) return false;
      if (!getFaceImg2()
          .equals(other.getFaceImg2())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FACE_IMG1_FIELD_NUMBER;
      hash = (53 * hash) + getFaceImg1().hashCode();
      hash = (37 * hash) + FACE_IMG2_FIELD_NUMBER;
      hash = (53 * hash) + getFaceImg2().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static faceRecognition.Face.CompareRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static faceRecognition.Face.CompareRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.CompareRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.CompareRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(faceRecognition.Face.CompareRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code faceRecognition.CompareRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:faceRecognition.CompareRequest)
        faceRecognition.Face.CompareRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return faceRecognition.Face.internal_static_faceRecognition_CompareRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return faceRecognition.Face.internal_static_faceRecognition_CompareRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                faceRecognition.Face.CompareRequest.class, faceRecognition.Face.CompareRequest.Builder.class);
      }

      // Construct using faceRecognition.Face.CompareRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        faceImg1_ = com.google.protobuf.ByteString.EMPTY;

        faceImg2_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return faceRecognition.Face.internal_static_faceRecognition_CompareRequest_descriptor;
      }

      @java.lang.Override
      public faceRecognition.Face.CompareRequest getDefaultInstanceForType() {
        return faceRecognition.Face.CompareRequest.getDefaultInstance();
      }

      @java.lang.Override
      public faceRecognition.Face.CompareRequest build() {
        faceRecognition.Face.CompareRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public faceRecognition.Face.CompareRequest buildPartial() {
        faceRecognition.Face.CompareRequest result = new faceRecognition.Face.CompareRequest(this);
        result.faceImg1_ = faceImg1_;
        result.faceImg2_ = faceImg2_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof faceRecognition.Face.CompareRequest) {
          return mergeFrom((faceRecognition.Face.CompareRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(faceRecognition.Face.CompareRequest other) {
        if (other == faceRecognition.Face.CompareRequest.getDefaultInstance()) return this;
        if (other.getFaceImg1() != com.google.protobuf.ByteString.EMPTY) {
          setFaceImg1(other.getFaceImg1());
        }
        if (other.getFaceImg2() != com.google.protobuf.ByteString.EMPTY) {
          setFaceImg2(other.getFaceImg2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        faceRecognition.Face.CompareRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (faceRecognition.Face.CompareRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString faceImg1_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes face_img1 = 1;</code>
       */
      public com.google.protobuf.ByteString getFaceImg1() {
        return faceImg1_;
      }
      /**
       * <code>bytes face_img1 = 1;</code>
       */
      public Builder setFaceImg1(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faceImg1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes face_img1 = 1;</code>
       */
      public Builder clearFaceImg1() {
        
        faceImg1_ = getDefaultInstance().getFaceImg1();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString faceImg2_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes face_img2 = 2;</code>
       */
      public com.google.protobuf.ByteString getFaceImg2() {
        return faceImg2_;
      }
      /**
       * <code>bytes face_img2 = 2;</code>
       */
      public Builder setFaceImg2(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faceImg2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes face_img2 = 2;</code>
       */
      public Builder clearFaceImg2() {
        
        faceImg2_ = getDefaultInstance().getFaceImg2();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:faceRecognition.CompareRequest)
    }

    // @@protoc_insertion_point(class_scope:faceRecognition.CompareRequest)
    private static final faceRecognition.Face.CompareRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new faceRecognition.Face.CompareRequest();
    }

    public static faceRecognition.Face.CompareRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompareRequest>
        PARSER = new com.google.protobuf.AbstractParser<CompareRequest>() {
      @java.lang.Override
      public CompareRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompareRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CompareRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompareRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public faceRecognition.Face.CompareRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CompareResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:faceRecognition.CompareResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 对比结果信任值 [0, 1.0]
     * </pre>
     *
     * <code>float confidence = 1;</code>
     */
    float getConfidence();
  }
  /**
   * Protobuf type {@code faceRecognition.CompareResponse}
   */
  public  static final class CompareResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:faceRecognition.CompareResponse)
      CompareResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CompareResponse.newBuilder() to construct.
    private CompareResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompareResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CompareResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CompareResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              confidence_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return faceRecognition.Face.internal_static_faceRecognition_CompareResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return faceRecognition.Face.internal_static_faceRecognition_CompareResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              faceRecognition.Face.CompareResponse.class, faceRecognition.Face.CompareResponse.Builder.class);
    }

    public static final int CONFIDENCE_FIELD_NUMBER = 1;
    private float confidence_;
    /**
     * <pre>
     * 对比结果信任值 [0, 1.0]
     * </pre>
     *
     * <code>float confidence = 1;</code>
     */
    public float getConfidence() {
      return confidence_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (confidence_ != 0F) {
        output.writeFloat(1, confidence_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (confidence_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, confidence_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof faceRecognition.Face.CompareResponse)) {
        return super.equals(obj);
      }
      faceRecognition.Face.CompareResponse other = (faceRecognition.Face.CompareResponse) obj;

      if (java.lang.Float.floatToIntBits(getConfidence())
          != java.lang.Float.floatToIntBits(
              other.getConfidence())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getConfidence());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static faceRecognition.Face.CompareResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static faceRecognition.Face.CompareResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.CompareResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.CompareResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(faceRecognition.Face.CompareResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code faceRecognition.CompareResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:faceRecognition.CompareResponse)
        faceRecognition.Face.CompareResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return faceRecognition.Face.internal_static_faceRecognition_CompareResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return faceRecognition.Face.internal_static_faceRecognition_CompareResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                faceRecognition.Face.CompareResponse.class, faceRecognition.Face.CompareResponse.Builder.class);
      }

      // Construct using faceRecognition.Face.CompareResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        confidence_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return faceRecognition.Face.internal_static_faceRecognition_CompareResponse_descriptor;
      }

      @java.lang.Override
      public faceRecognition.Face.CompareResponse getDefaultInstanceForType() {
        return faceRecognition.Face.CompareResponse.getDefaultInstance();
      }

      @java.lang.Override
      public faceRecognition.Face.CompareResponse build() {
        faceRecognition.Face.CompareResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public faceRecognition.Face.CompareResponse buildPartial() {
        faceRecognition.Face.CompareResponse result = new faceRecognition.Face.CompareResponse(this);
        result.confidence_ = confidence_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof faceRecognition.Face.CompareResponse) {
          return mergeFrom((faceRecognition.Face.CompareResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(faceRecognition.Face.CompareResponse other) {
        if (other == faceRecognition.Face.CompareResponse.getDefaultInstance()) return this;
        if (other.getConfidence() != 0F) {
          setConfidence(other.getConfidence());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        faceRecognition.Face.CompareResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (faceRecognition.Face.CompareResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float confidence_ ;
      /**
       * <pre>
       * 对比结果信任值 [0, 1.0]
       * </pre>
       *
       * <code>float confidence = 1;</code>
       */
      public float getConfidence() {
        return confidence_;
      }
      /**
       * <pre>
       * 对比结果信任值 [0, 1.0]
       * </pre>
       *
       * <code>float confidence = 1;</code>
       */
      public Builder setConfidence(float value) {
        
        confidence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 对比结果信任值 [0, 1.0]
       * </pre>
       *
       * <code>float confidence = 1;</code>
       */
      public Builder clearConfidence() {
        
        confidence_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:faceRecognition.CompareResponse)
    }

    // @@protoc_insertion_point(class_scope:faceRecognition.CompareResponse)
    private static final faceRecognition.Face.CompareResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new faceRecognition.Face.CompareResponse();
    }

    public static faceRecognition.Face.CompareResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompareResponse>
        PARSER = new com.google.protobuf.AbstractParser<CompareResponse>() {
      @java.lang.Override
      public CompareResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CompareResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CompareResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompareResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public faceRecognition.Face.CompareResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:faceRecognition.SearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * FaceSet.id
     * </pre>
     *
     * <code>string face_set_id = 1;</code>
     */
    java.lang.String getFaceSetId();
    /**
     * <pre>
     * FaceSet.id
     * </pre>
     *
     * <code>string face_set_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getFaceSetIdBytes();

    /**
     * <pre>
     * 待搜索人脸图片
     * </pre>
     *
     * <code>bytes face_img = 2;</code>
     */
    com.google.protobuf.ByteString getFaceImg();
  }
  /**
   * Protobuf type {@code faceRecognition.SearchRequest}
   */
  public  static final class SearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:faceRecognition.SearchRequest)
      SearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchRequest() {
      faceSetId_ = "";
      faceImg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              faceSetId_ = s;
              break;
            }
            case 18: {

              faceImg_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return faceRecognition.Face.internal_static_faceRecognition_SearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return faceRecognition.Face.internal_static_faceRecognition_SearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              faceRecognition.Face.SearchRequest.class, faceRecognition.Face.SearchRequest.Builder.class);
    }

    public static final int FACE_SET_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object faceSetId_;
    /**
     * <pre>
     * FaceSet.id
     * </pre>
     *
     * <code>string face_set_id = 1;</code>
     */
    public java.lang.String getFaceSetId() {
      java.lang.Object ref = faceSetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faceSetId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * FaceSet.id
     * </pre>
     *
     * <code>string face_set_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFaceSetIdBytes() {
      java.lang.Object ref = faceSetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faceSetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FACE_IMG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString faceImg_;
    /**
     * <pre>
     * 待搜索人脸图片
     * </pre>
     *
     * <code>bytes face_img = 2;</code>
     */
    public com.google.protobuf.ByteString getFaceImg() {
      return faceImg_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFaceSetIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, faceSetId_);
      }
      if (!faceImg_.isEmpty()) {
        output.writeBytes(2, faceImg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFaceSetIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, faceSetId_);
      }
      if (!faceImg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, faceImg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof faceRecognition.Face.SearchRequest)) {
        return super.equals(obj);
      }
      faceRecognition.Face.SearchRequest other = (faceRecognition.Face.SearchRequest) obj;

      if (!getFaceSetId()
          .equals(other.getFaceSetId())) return false;
      if (!getFaceImg()
          .equals(other.getFaceImg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FACE_SET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFaceSetId().hashCode();
      hash = (37 * hash) + FACE_IMG_FIELD_NUMBER;
      hash = (53 * hash) + getFaceImg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static faceRecognition.Face.SearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static faceRecognition.Face.SearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.SearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.SearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(faceRecognition.Face.SearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code faceRecognition.SearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:faceRecognition.SearchRequest)
        faceRecognition.Face.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return faceRecognition.Face.internal_static_faceRecognition_SearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return faceRecognition.Face.internal_static_faceRecognition_SearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                faceRecognition.Face.SearchRequest.class, faceRecognition.Face.SearchRequest.Builder.class);
      }

      // Construct using faceRecognition.Face.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        faceSetId_ = "";

        faceImg_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return faceRecognition.Face.internal_static_faceRecognition_SearchRequest_descriptor;
      }

      @java.lang.Override
      public faceRecognition.Face.SearchRequest getDefaultInstanceForType() {
        return faceRecognition.Face.SearchRequest.getDefaultInstance();
      }

      @java.lang.Override
      public faceRecognition.Face.SearchRequest build() {
        faceRecognition.Face.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public faceRecognition.Face.SearchRequest buildPartial() {
        faceRecognition.Face.SearchRequest result = new faceRecognition.Face.SearchRequest(this);
        result.faceSetId_ = faceSetId_;
        result.faceImg_ = faceImg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof faceRecognition.Face.SearchRequest) {
          return mergeFrom((faceRecognition.Face.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(faceRecognition.Face.SearchRequest other) {
        if (other == faceRecognition.Face.SearchRequest.getDefaultInstance()) return this;
        if (!other.getFaceSetId().isEmpty()) {
          faceSetId_ = other.faceSetId_;
          onChanged();
        }
        if (other.getFaceImg() != com.google.protobuf.ByteString.EMPTY) {
          setFaceImg(other.getFaceImg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        faceRecognition.Face.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (faceRecognition.Face.SearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object faceSetId_ = "";
      /**
       * <pre>
       * FaceSet.id
       * </pre>
       *
       * <code>string face_set_id = 1;</code>
       */
      public java.lang.String getFaceSetId() {
        java.lang.Object ref = faceSetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          faceSetId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * FaceSet.id
       * </pre>
       *
       * <code>string face_set_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFaceSetIdBytes() {
        java.lang.Object ref = faceSetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          faceSetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * FaceSet.id
       * </pre>
       *
       * <code>string face_set_id = 1;</code>
       */
      public Builder setFaceSetId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faceSetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * FaceSet.id
       * </pre>
       *
       * <code>string face_set_id = 1;</code>
       */
      public Builder clearFaceSetId() {
        
        faceSetId_ = getDefaultInstance().getFaceSetId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * FaceSet.id
       * </pre>
       *
       * <code>string face_set_id = 1;</code>
       */
      public Builder setFaceSetIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        faceSetId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString faceImg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 待搜索人脸图片
       * </pre>
       *
       * <code>bytes face_img = 2;</code>
       */
      public com.google.protobuf.ByteString getFaceImg() {
        return faceImg_;
      }
      /**
       * <pre>
       * 待搜索人脸图片
       * </pre>
       *
       * <code>bytes face_img = 2;</code>
       */
      public Builder setFaceImg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faceImg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 待搜索人脸图片
       * </pre>
       *
       * <code>bytes face_img = 2;</code>
       */
      public Builder clearFaceImg() {
        
        faceImg_ = getDefaultInstance().getFaceImg();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:faceRecognition.SearchRequest)
    }

    // @@protoc_insertion_point(class_scope:faceRecognition.SearchRequest)
    private static final faceRecognition.Face.SearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new faceRecognition.Face.SearchRequest();
    }

    public static faceRecognition.Face.SearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SearchRequest>() {
      @java.lang.Override
      public SearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public faceRecognition.Face.SearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:faceRecognition.SearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 搜索结果信任值 [0, 1.0]
     * </pre>
     *
     * <code>float confidence = 1;</code>
     */
    float getConfidence();

    /**
     * <pre>
     * 搜索结果FaceDetail.token
     * </pre>
     *
     * <code>string face_token = 2;</code>
     */
    java.lang.String getFaceToken();
    /**
     * <pre>
     * 搜索结果FaceDetail.token
     * </pre>
     *
     * <code>string face_token = 2;</code>
     */
    com.google.protobuf.ByteString
        getFaceTokenBytes();
  }
  /**
   * Protobuf type {@code faceRecognition.SearchResponse}
   */
  public  static final class SearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:faceRecognition.SearchResponse)
      SearchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchResponse() {
      faceToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              confidence_ = input.readFloat();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              faceToken_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return faceRecognition.Face.internal_static_faceRecognition_SearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return faceRecognition.Face.internal_static_faceRecognition_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              faceRecognition.Face.SearchResponse.class, faceRecognition.Face.SearchResponse.Builder.class);
    }

    public static final int CONFIDENCE_FIELD_NUMBER = 1;
    private float confidence_;
    /**
     * <pre>
     * 搜索结果信任值 [0, 1.0]
     * </pre>
     *
     * <code>float confidence = 1;</code>
     */
    public float getConfidence() {
      return confidence_;
    }

    public static final int FACE_TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object faceToken_;
    /**
     * <pre>
     * 搜索结果FaceDetail.token
     * </pre>
     *
     * <code>string face_token = 2;</code>
     */
    public java.lang.String getFaceToken() {
      java.lang.Object ref = faceToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        faceToken_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 搜索结果FaceDetail.token
     * </pre>
     *
     * <code>string face_token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFaceTokenBytes() {
      java.lang.Object ref = faceToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        faceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (confidence_ != 0F) {
        output.writeFloat(1, confidence_);
      }
      if (!getFaceTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, faceToken_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (confidence_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, confidence_);
      }
      if (!getFaceTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, faceToken_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof faceRecognition.Face.SearchResponse)) {
        return super.equals(obj);
      }
      faceRecognition.Face.SearchResponse other = (faceRecognition.Face.SearchResponse) obj;

      if (java.lang.Float.floatToIntBits(getConfidence())
          != java.lang.Float.floatToIntBits(
              other.getConfidence())) return false;
      if (!getFaceToken()
          .equals(other.getFaceToken())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getConfidence());
      hash = (37 * hash) + FACE_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getFaceToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static faceRecognition.Face.SearchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static faceRecognition.Face.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static faceRecognition.Face.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(faceRecognition.Face.SearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code faceRecognition.SearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:faceRecognition.SearchResponse)
        faceRecognition.Face.SearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return faceRecognition.Face.internal_static_faceRecognition_SearchResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return faceRecognition.Face.internal_static_faceRecognition_SearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                faceRecognition.Face.SearchResponse.class, faceRecognition.Face.SearchResponse.Builder.class);
      }

      // Construct using faceRecognition.Face.SearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        confidence_ = 0F;

        faceToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return faceRecognition.Face.internal_static_faceRecognition_SearchResponse_descriptor;
      }

      @java.lang.Override
      public faceRecognition.Face.SearchResponse getDefaultInstanceForType() {
        return faceRecognition.Face.SearchResponse.getDefaultInstance();
      }

      @java.lang.Override
      public faceRecognition.Face.SearchResponse build() {
        faceRecognition.Face.SearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public faceRecognition.Face.SearchResponse buildPartial() {
        faceRecognition.Face.SearchResponse result = new faceRecognition.Face.SearchResponse(this);
        result.confidence_ = confidence_;
        result.faceToken_ = faceToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof faceRecognition.Face.SearchResponse) {
          return mergeFrom((faceRecognition.Face.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(faceRecognition.Face.SearchResponse other) {
        if (other == faceRecognition.Face.SearchResponse.getDefaultInstance()) return this;
        if (other.getConfidence() != 0F) {
          setConfidence(other.getConfidence());
        }
        if (!other.getFaceToken().isEmpty()) {
          faceToken_ = other.faceToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        faceRecognition.Face.SearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (faceRecognition.Face.SearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float confidence_ ;
      /**
       * <pre>
       * 搜索结果信任值 [0, 1.0]
       * </pre>
       *
       * <code>float confidence = 1;</code>
       */
      public float getConfidence() {
        return confidence_;
      }
      /**
       * <pre>
       * 搜索结果信任值 [0, 1.0]
       * </pre>
       *
       * <code>float confidence = 1;</code>
       */
      public Builder setConfidence(float value) {
        
        confidence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索结果信任值 [0, 1.0]
       * </pre>
       *
       * <code>float confidence = 1;</code>
       */
      public Builder clearConfidence() {
        
        confidence_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object faceToken_ = "";
      /**
       * <pre>
       * 搜索结果FaceDetail.token
       * </pre>
       *
       * <code>string face_token = 2;</code>
       */
      public java.lang.String getFaceToken() {
        java.lang.Object ref = faceToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          faceToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 搜索结果FaceDetail.token
       * </pre>
       *
       * <code>string face_token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFaceTokenBytes() {
        java.lang.Object ref = faceToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          faceToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 搜索结果FaceDetail.token
       * </pre>
       *
       * <code>string face_token = 2;</code>
       */
      public Builder setFaceToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        faceToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索结果FaceDetail.token
       * </pre>
       *
       * <code>string face_token = 2;</code>
       */
      public Builder clearFaceToken() {
        
        faceToken_ = getDefaultInstance().getFaceToken();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索结果FaceDetail.token
       * </pre>
       *
       * <code>string face_token = 2;</code>
       */
      public Builder setFaceTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        faceToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:faceRecognition.SearchResponse)
    }

    // @@protoc_insertion_point(class_scope:faceRecognition.SearchResponse)
    private static final faceRecognition.Face.SearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new faceRecognition.Face.SearchResponse();
    }

    public static faceRecognition.Face.SearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
      @java.lang.Override
      public SearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public faceRecognition.Face.SearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_faceRecognition_CompareRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_faceRecognition_CompareRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_faceRecognition_CompareResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_faceRecognition_CompareResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_faceRecognition_SearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_faceRecognition_SearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_faceRecognition_SearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_faceRecognition_SearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nface.proto\022\017faceRecognition\032\034google/ap" +
      "i/annotations.proto\"6\n\016CompareRequest\022\021\n" +
      "\tface_img1\030\001 \001(\014\022\021\n\tface_img2\030\002 \001(\014\"%\n\017C" +
      "ompareResponse\022\022\n\nconfidence\030\001 \001(\002\"6\n\rSe" +
      "archRequest\022\023\n\013face_set_id\030\001 \001(\t\022\020\n\010face" +
      "_img\030\002 \001(\014\"8\n\016SearchResponse\022\022\n\nconfiden" +
      "ce\030\001 \001(\002\022\022\n\nface_token\030\002 \001(\t2\347\001\n\013FaceSer" +
      "vice\022m\n\007Compare\022\037.faceRecognition.Compar" +
      "eRequest\032 .faceRecognition.CompareRespon" +
      "se\"\037\202\323\344\223\002\031\"\024/api/v2/face/compare:\001*\022i\n\006S" +
      "earch\022\036.faceRecognition.SearchRequest\032\037." +
      "faceRecognition.SearchResponse\"\036\202\323\344\223\002\030\"\023" +
      "/api/v2/face/search:\001*b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_faceRecognition_CompareRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_faceRecognition_CompareRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_faceRecognition_CompareRequest_descriptor,
        new java.lang.String[] { "FaceImg1", "FaceImg2", });
    internal_static_faceRecognition_CompareResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_faceRecognition_CompareResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_faceRecognition_CompareResponse_descriptor,
        new java.lang.String[] { "Confidence", });
    internal_static_faceRecognition_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_faceRecognition_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_faceRecognition_SearchRequest_descriptor,
        new java.lang.String[] { "FaceSetId", "FaceImg", });
    internal_static_faceRecognition_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_faceRecognition_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_faceRecognition_SearchResponse_descriptor,
        new java.lang.String[] { "Confidence", "FaceToken", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
