# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: escpos.proto for package 'escposService'

require 'grpc'
require 'escpos_pb'

module EscposService
  module EscPosService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'escposService.EscPosService'

      # 打印bytes数据
      # 打印模板与打印对象方式不满足业务需求
      # 或希望接入其它已外部业务实现的打印组件时, 可通过此方法直接
      # 传入打印内容
      rpc :PrintRaw, PrintRawRequest, PrintRawResponse
      # 打印对象
      rpc :PrintElements, PrintElementsRequest, PrintElementsResponse
      # 打印预设的html模板内容
      rpc :PrintHtmlTemplate, PrintHtmlTemplateRequest, PrintHtmlTemplateResponse
      # 创建html模板
      rpc :NewHtmlTemplate, NewHtmlTemplateRequest, NewHtmlTemplateResponse
      # 获取html模板列表
      rpc :ListHtmlTemplates, ListHtmlTemplatesRequest, ListHtmlTemplatesResponse
      # 获取指定html模板内容
      rpc :GetHtmlTemplate, GetHtmlTemplateRequest, GetHtmlTemplateResponse
      # 更新html模板
      rpc :UpdateHtmlTemplate, UpdateHtmlTemplateRequest, UpdateHtmlTemplateResponse
      # 删除html模板
      rpc :DeleteHtmlTemplates, DeleteHtmlTemplatesRequest, DeleteHtmlTemplatesResponse
    end

    Stub = Service.rpc_stub_class
  end
end
