# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("network.proto", :syntax => :proto3) do
    add_message "networkService.NetworkInfo" do
      optional :name, :string, 1
      optional :mac, :string, 2
      optional :channel, :uint32, 3
      optional :rssi, :uint32, 4
    end
    add_message "networkService.ListNetworksRequest" do
    end
    add_message "networkService.ListNetworksResponse" do
      repeated :networks_info, :message, 1, "networkService.NetworkInfo"
    end
    add_message "networkService.ConnectRequest" do
      optional :network_info, :message, 1, "networkService.NetworkInfo"
      optional :ssid, :string, 3
      optional :pwd, :string, 2
      optional :keep_alive, :bool, 4
      optional :keep_alive_interval, :uint32, 5
    end
    add_message "networkService.NetworkStatus" do
      optional :status, :enum, 1, "networkService.Status"
      optional :name, :string, 2
      optional :public_ip, :string, 3
      optional :rssi, :uint32, 4
      optional :upload, :uint32, 5
      optional :download, :uint32, 6
    end
    add_message "networkService.ConnectResponse" do
    end
    add_message "networkService.GetStatusRequest" do
    end
    add_message "networkService.GetStatusResponse" do
      optional :network_status, :message, 1, "networkService.NetworkStatus"
    end
    add_message "networkService.NetworkDeviceInfo" do
      optional :ssid, :string, 1
      optional :credential, :string, 2
    end
    add_message "networkService.GetNetworkDeviceInfoRequest" do
      optional :with_credential, :bool, 1
    end
    add_message "networkService.GetNetworkDeviceInfoResponse" do
      optional :network_device_info, :message, 1, "networkService.NetworkDeviceInfo"
    end
    add_message "networkService.UpdateNetworkDeviceInfoRequest" do
      optional :network_device_info, :message, 1, "networkService.NetworkDeviceInfo"
    end
    add_message "networkService.UpdateNetworkDeviceInfoResponse" do
    end
    add_enum "networkService.Status" do
      value :UNKNOWN, 0
      value :DISCONNECTED, 1
      value :CONNECTING, 2
      value :CONNECTED, 3
    end
  end
end

module NetworkService
  NetworkInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.NetworkInfo").msgclass
  ListNetworksRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.ListNetworksRequest").msgclass
  ListNetworksResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.ListNetworksResponse").msgclass
  ConnectRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.ConnectRequest").msgclass
  NetworkStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.NetworkStatus").msgclass
  ConnectResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.ConnectResponse").msgclass
  GetStatusRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.GetStatusRequest").msgclass
  GetStatusResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.GetStatusResponse").msgclass
  NetworkDeviceInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.NetworkDeviceInfo").msgclass
  GetNetworkDeviceInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.GetNetworkDeviceInfoRequest").msgclass
  GetNetworkDeviceInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.GetNetworkDeviceInfoResponse").msgclass
  UpdateNetworkDeviceInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.UpdateNetworkDeviceInfoRequest").msgclass
  UpdateNetworkDeviceInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.UpdateNetworkDeviceInfoResponse").msgclass
  Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("networkService.Status").enummodule
end
