// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xcodescanner.proto

package com.jjrobot.andy4.xcodescannerpb;

public final class XCodeScannerServicePB {
  private XCodeScannerServicePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetScanDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xcScannerService.GetScanDataRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code xcScannerService.GetScanDataRequest}
   */
  public  static final class GetScanDataRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xcScannerService.GetScanDataRequest)
      GetScanDataRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetScanDataRequest.newBuilder() to construct.
    private GetScanDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetScanDataRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetScanDataRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetScanDataRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest.class, com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest)) {
        return super.equals(obj);
      }
      com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest other = (com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code xcScannerService.GetScanDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xcScannerService.GetScanDataRequest)
        com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest.class, com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest.Builder.class);
      }

      // Construct using com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataRequest_descriptor;
      }

      @java.lang.Override
      public com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest getDefaultInstanceForType() {
        return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest build() {
        com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest buildPartial() {
        com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest result = new com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest) {
          return mergeFrom((com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest other) {
        if (other == com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xcScannerService.GetScanDataRequest)
    }

    // @@protoc_insertion_point(class_scope:xcScannerService.GetScanDataRequest)
    private static final com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest();
    }

    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetScanDataRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetScanDataRequest>() {
      @java.lang.Override
      public GetScanDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetScanDataRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetScanDataRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetScanDataRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetScanDataResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:xcScannerService.GetScanDataResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string content = 1;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 1;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * <pre>
   * 扫码结果
   * </pre>
   *
   * Protobuf type {@code xcScannerService.GetScanDataResponse}
   */
  public  static final class GetScanDataResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:xcScannerService.GetScanDataResponse)
      GetScanDataResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetScanDataResponse.newBuilder() to construct.
    private GetScanDataResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetScanDataResponse() {
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GetScanDataResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetScanDataResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse.class, com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 1;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 1;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse)) {
        return super.equals(obj);
      }
      com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse other = (com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse) obj;

      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 扫码结果
     * </pre>
     *
     * Protobuf type {@code xcScannerService.GetScanDataResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:xcScannerService.GetScanDataResponse)
        com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse.class, com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse.Builder.class);
      }

      // Construct using com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.internal_static_xcScannerService_GetScanDataResponse_descriptor;
      }

      @java.lang.Override
      public com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse getDefaultInstanceForType() {
        return com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse build() {
        com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse buildPartial() {
        com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse result = new com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse(this);
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse) {
          return mergeFrom((com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse other) {
        if (other == com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse.getDefaultInstance()) return this;
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 1;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 1;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 1;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 1;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:xcScannerService.GetScanDataResponse)
    }

    // @@protoc_insertion_point(class_scope:xcScannerService.GetScanDataResponse)
    private static final com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse();
    }

    public static com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetScanDataResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetScanDataResponse>() {
      @java.lang.Override
      public GetScanDataResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetScanDataResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetScanDataResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetScanDataResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.jjrobot.andy4.xcodescannerpb.XCodeScannerServicePB.GetScanDataResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xcScannerService_GetScanDataRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xcScannerService_GetScanDataRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xcScannerService_GetScanDataResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xcScannerService_GetScanDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022xcodescanner.proto\022\020xcScannerService\"\024" +
      "\n\022GetScanDataRequest\"&\n\023GetScanDataRespo" +
      "nse\022\017\n\007content\030\001 \001(\t2u\n\023XCodeScannerServ" +
      "ice\022^\n\013GetScanData\022$.xcScannerService.Ge" +
      "tScanDataRequest\032%.xcScannerService.GetS" +
      "canDataResponse\"\0000\001BI\n com.jjrobot.andy4" +
      ".xcodescannerpbB\025XCodeScannerServicePBZ\016" +
      "xcodescannerpbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xcScannerService_GetScanDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xcScannerService_GetScanDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xcScannerService_GetScanDataRequest_descriptor,
        new java.lang.String[] { });
    internal_static_xcScannerService_GetScanDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xcScannerService_GetScanDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xcScannerService_GetScanDataResponse_descriptor,
        new java.lang.String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
